<?php

namespace Database\Seeders;

use App\Models\Region;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $regions = [
            // ["city_id"=>"1","city"=>"15 May"],
            // ["city_id"=>"1","city"=>"Al Azbakeyah"],
            // ["city_id"=>"1","city"=>"Al Basatin"],
            // ["city_id"=>"1","city"=>"Tebin"],
            // ["city_id"=>"1","city"=>"El-Khalifa"],
            // ["city_id"=>"1","city"=>"El darrasa"],
            // ["city_id"=>"1","city"=>"Aldarb Alahmar"],
            // ["city_id"=>"1","city"=>"Zawya al-Hamra"],
            // ["city_id"=>"1","city"=>"El-Zaytoun"],
            // ["city_id"=>"1","city"=>"Sahel"],
            // ["city_id"=>"1","city"=>"El Salam"],
            // ["city_id"=>"1","city"=>"Sayeda Zeinab"],
            // ["city_id"=>"1","city"=>"El Sharabeya"],
            // ["city_id"=>"1","city"=>"Shorouk"],
            // ["city_id"=>"1","city"=>"El Daher"],
            // ["city_id"=>"1","city"=>"Ataba"],
            // ["city_id"=>"1","city"=>"New Cairo"],
            // ["city_id"=>"1","city"=>"El Marg"],
            // ["city_id"=>"1","city"=>"Ezbet el Nakhl"],
            // ["city_id"=>"1","city"=>"Matareya"],
            // ["city_id"=>"1","city"=>"Maadi"],
            // ["city_id"=>"1","city"=>"Maasara"],
            // ["city_id"=>"1","city"=>"Mokattam"],
            // ["city_id"=>"1","city"=>"Manyal"],
            // ["city_id"=>"1","city"=>"Mosky"],
            // ["city_id"=>"1","city"=>"Nozha"],
            // ["city_id"=>"1","city"=>"Waily"],
            // ["city_id"=>"1","city"=>"Bab al-Shereia"],
            // ["city_id"=>"1","city"=>"Bolaq"],
            // ["city_id"=>"1","city"=>"Garden City"],
            // ["city_id"=>"1","city"=>"Hadayek El-Kobba"],
            // ["city_id"=>"1","city"=>"Helwan"],
            // ["city_id"=>"1","city"=>"Dar Al Salam"],
            ["city_id"=>"1","region"=>"شبرا"],
            ["city_id"=>"1","region"=>"طره"],
            ["city_id"=>"1","region"=>"عابدين"],
            ["city_id"=>"1","region"=>"عباسية"],
            ["city_id"=>"1","region"=>"عين شمس"],
            ["city_id"=>"1","region"=>"مدينة نصر"],
            ["city_id"=>"1","region"=>"مصر الجديدة"],
            ["city_id"=>"1","region"=>"مصر القديمة"],
            ["city_id"=>"1","region"=>"منشية ناصر"],
            ["city_id"=>"1","region"=>"مدينة بدر"],
            ["city_id"=>"1","region"=>"مدينة العبور"],
            ["city_id"=>"1","region"=>"وسط البلد"],
            // ["id"=>"46","city_id"=>"1","region"=>"الزمالك","city"=>"Zamalek"],
            // ["id"=>"47","city_id"=>"1","region"=>"قصر النيل","city"=>"Kasr El Nile"],
            // ["id"=>"48","city_id"=>"1","region"=>"الرحاب","city"=>"Rehab"],
            // ["id"=>"49","city_id"=>"1","region"=>"القطامية","city"=>"Katameya"],
            // ["id"=>"50","city_id"=>"1","region"=>"مدينتي","city"=>"Madinty"],
            // ["id"=>"51","city_id"=>"1","region"=>"روض الفرج","city"=>"Rod Alfarag"],
            // ["id"=>"52","city_id"=>"1","region"=>"شيراتون","city"=>"Sheraton"],
            // ["id"=>"53","city_id"=>"1","region"=>"الجمالية","city"=>"El-Gamaleya"],
            // ["id"=>"54","city_id"=>"1","region"=>"العاشر من رمضان","city"=>"10th of Ramadan City"],
            // ["id"=>"55","city_id"=>"1","region"=>"الحلمية","city"=>"Helmeyat Alzaytoun"],
            // ["id"=>"56","city_id"=>"1","region"=>"النزهة الجديدة","city"=>"New Nozha"],
            // ["id"=>"57","city_id"=>"1","region"=>"العاصمة الإدارية","city"=>"Capital New"],
            ["city_id"=>"2","region"=>"الجيزة"],
            ["city_id"=>"2","region"=>"السادس من أكتوبر"],
            ["city_id"=>"2","region"=>"الشيخ زايد"],
            ["city_id"=>"2","region"=>"الحوامدية"],
            ["city_id"=>"2","region"=>"البدرشين"],
            // ["city_id"=>"2","region"=>"الصف","city"=>"Saf"],
            // ["city_id"=>"2","region"=>"أطفيح","city"=>"Atfih"],
            // ["city_id"=>"2","region"=>"العياط","city"=>"Al Ayat"],
            // ["city_id"=>"2","region"=>"الباويطي","city"=>"Al-Bawaiti"],
            // ["city_id"=>"2","region"=>"منشأة القناطر","city"=>"ManshiyetAl Qanater"],
            // ["city_id"=>"2","region"=>"أوسيم","city"=>"Oaseem"],
            // ["city_id"=>"2","region"=>"كرداسة","city"=>"Kerdasa"],
            // ["id"=>"70","city_id"=>"2","region"=>"أبو النمرس","city"=>"Abu Nomros"],
            // ["id"=>"71","city_id"=>"2","region"=>"كفر غطاطي","city"=>"Kafr Ghati"],
            // ["id"=>"72","city_id"=>"2","region"=>"منشأة البكاري","city"=>"Manshiyet Al Bakari"],
            // ["id"=>"73","city_id"=>"2","region"=>"الدقى","city"=>"Dokki"],
            // ["id"=>"74","city_id"=>"2","region"=>"العجوزة","city"=>"Agouza"],
            // ["id"=>"75","city_id"=>"2","region"=>"الهرم","city"=>"Haram"],
            // ["id"=>"76","city_id"=>"2","region"=>"الوراق","city"=>"Warraq"],
            // ["id"=>"77","city_id"=>"2","region"=>"امبابة","city"=>"Imbaba"],
            // ["id"=>"78","city_id"=>"2","region"=>"بولاق الدكرور","city"=>"Boulaq Dakrour"],
            // ["id"=>"79","city_id"=>"2","region"=>"الواحات البحرية","city"=>"Al Wahat Al Baharia"],
            // ["id"=>"80","city_id"=>"2","region"=>"العمرانية","city"=>"Omraneya"],
            // ["id"=>"81","city_id"=>"2","region"=>"المنيب","city"=>"Moneeb"],
            // ["id"=>"82","city_id"=>"2","region"=>"بين السرايات","city"=>"Bin Alsarayat"],
            // ["id"=>"83","city_id"=>"2","region"=>"الكيت كات","city"=>"Kit Kat"],
            // ["id"=>"84","city_id"=>"2","region"=>"المهندسين","city"=>"Mohandessin"],
            // ["id"=>"85","city_id"=>"2","region"=>"فيصل","city"=>"Faisal"],
            // ["id"=>"86","city_id"=>"2","region"=>"أبو رواش","city"=>"Abu Rawash"],
            // ["id"=>"87","city_id"=>"2","region"=>"حدائق الأهرام","city"=>"Hadayek Alahram"],
            // ["id"=>"88","city_id"=>"2","region"=>"الحرانية","city"=>"Haraneya"],
            // ["id"=>"89","city_id"=>"2","region"=>"حدائق اكتوبر","city"=>"Hadayek October"],
            // ["id"=>"90","city_id"=>"2","region"=>"صفط اللبن","city"=>"Saft Allaban"],
            // ["id"=>"91","city_id"=>"2","region"=>"القرية الذكية","city"=>"Smart Village"],
            // ["id"=>"92","city_id"=>"2","region"=>"ارض اللواء","city"=>"Ard Ellwaa"],
            // ["id"=>"93","city_id"=>"3","region"=>"ابو قير","city"=>"Abu Qir"],
            // ["id"=>"94","city_id"=>"3","region"=>"الابراهيمية","city"=>"Al Ibrahimeyah"],
            // ["id"=>"95","city_id"=>"3","region"=>"الأزاريطة","city"=>"Azarita"],
            // ["id"=>"96","city_id"=>"3","region"=>"الانفوشى","city"=>"Anfoushi"],
            // ["id"=>"97","city_id"=>"3","region"=>"الدخيلة","city"=>"Dekheila"],
            // ["id"=>"98","city_id"=>"3","region"=>"السيوف","city"=>"El Soyof"],
            // ["id"=>"99","city_id"=>"3","region"=>"العامرية","city"=>"Ameria"],
            // ["id"=>"100","city_id"=>"3","region"=>"اللبان","city"=>"El Labban"],
            // ["id"=>"101","city_id"=>"3","region"=>"المفروزة","city"=>"Al Mafrouza"],
            // ["id"=>"102","city_id"=>"3","region"=>"المنتزه","city"=>"El Montaza"],
            // ["id"=>"103","city_id"=>"3","region"=>"المنشية","city"=>"Mansheya"],
            // ["id"=>"104","city_id"=>"3","region"=>"الناصرية","city"=>"Naseria"],
            // ["id"=>"105","city_id"=>"3","region"=>"امبروزو","city"=>"Ambrozo"],
            // ["id"=>"106","city_id"=>"3","region"=>"باب شرق","city"=>"Bab Sharq"],
            ["city_id"=>"3","region"=>"برج العرب"],
            ["city_id"=>"3","region"=>"ستانلى"],
            ["city_id"=>"3","region"=>"سموحة"],
            ["city_id"=>"3","region"=>"سيدى بشر"],
            // ["city_id"=>"3","region"=>"شدس"],
            // ["id"=>"112","city_id"=>"3","region"=>"غيط العنب","city"=>"Gheet Alenab"],
            // ["id"=>"113","city_id"=>"3","region"=>"فلمينج","city"=>"Fleming"],
            // ["id"=>"114","city_id"=>"3","region"=>"فيكتوريا","city"=>"Victoria"],
            // ["id"=>"115","city_id"=>"3","region"=>"كامب شيزار","city"=>"Camp Shizar"],
            // ["id"=>"116","city_id"=>"3","region"=>"كرموز","city"=>"Karmooz"],
            // ["id"=>"117","city_id"=>"3","region"=>"محطة الرمل","city"=>"Mahta Alraml"],
            // ["id"=>"118","city_id"=>"3","region"=>"مينا البصل","city"=>"Mina El-Basal"],
            // ["id"=>"119","city_id"=>"3","region"=>"العصافرة","city"=>"Asafra"],
            // ["id"=>"120","city_id"=>"3","region"=>"العجمي","city"=>"Agamy"],
            // ["id"=>"121","city_id"=>"3","region"=>"بكوس","city"=>"Bakos"],
            // ["id"=>"122","city_id"=>"3","region"=>"بولكلي","city"=>"Boulkly"],
            // ["id"=>"123","city_id"=>"3","region"=>"كليوباترا","city"=>"Cleopatra"],
            // ["id"=>"124","city_id"=>"3","region"=>"جليم","city"=>"Glim"],
            // ["id"=>"125","city_id"=>"3","region"=>"المعمورة","city"=>"Al Mamurah"],
            // ["id"=>"126","city_id"=>"3","region"=>"المندرة","city"=>"Al Mandara"],
            // ["id"=>"127","city_id"=>"3","region"=>"محرم بك","city"=>"Moharam Bek"],
            // ["id"=>"128","city_id"=>"3","region"=>"الشاطبي","city"=>"Elshatby"],
            // ["id"=>"129","city_id"=>"3","region"=>"سيدي جابر","city"=>"Sidi Gaber"],
            // ["id"=>"130","city_id"=>"3","region"=>"الساحل الشمالي","city"=>"North Coast\/sahel"],
            // ["id"=>"131","city_id"=>"3","region"=>"الحضرة","city"=>"Alhadra"],
            // ["id"=>"132","city_id"=>"3","region"=>"العطارين","city"=>"Alattarin"],
            // ["id"=>"133","city_id"=>"3","region"=>"سيدي كرير","city"=>"Sidi Kerir"],
            // ["id"=>"134","city_id"=>"3","region"=>"الجمرك","city"=>"Elgomrok"],
            // ["id"=>"135","city_id"=>"3","region"=>"المكس","city"=>"Al Max"],
            // ["id"=>"136","city_id"=>"3","region"=>"مارينا","city"=>"Marina"],
            ["city_id"=>"4","region"=>"المنصورة"],
            // ["id"=>"138","city_id"=>"4","region"=>"طلخا","city"=>"Talkha"],
            // ["id"=>"139","city_id"=>"4","region"=>"ميت غمر","city"=>"Mitt Ghamr"],
            // ["id"=>"140","city_id"=>"4","region"=>"دكرنس","city"=>"Dekernes"],
            // ["id"=>"141","city_id"=>"4","region"=>"أجا","city"=>"Aga"],
            // ["id"=>"142","city_id"=>"4","region"=>"منية النصر","city"=>"Menia El Nasr"],
            ["city_id"=>"4","region"=>"السنبلاوين"],
            // ["id"=>"144","city_id"=>"4","region"=>"الكردي","city"=>"El Kurdi"],
            // ["id"=>"145","city_id"=>"4","region"=>"بني عبيد","city"=>"Bani Ubaid"],
            // ["id"=>"146","city_id"=>"4","region"=>"المنزلة","city"=>"Al Manzala"],
            // ["id"=>"147","city_id"=>"4","region"=>"تمي الأمديد","city"=>"tami al'amdid"],
            // ["id"=>"148","city_id"=>"4","region"=>"الجمالية","city"=>"aljamalia"],
            // ["id"=>"149","city_id"=>"4","region"=>"شربين","city"=>"Sherbin"],
            // ["id"=>"150","city_id"=>"4","region"=>"المطرية","city"=>"Mataria"],
            // ["id"=>"151","city_id"=>"4","region"=>"بلقاس","city"=>"Belqas"],
            // ["id"=>"152","city_id"=>"4","region"=>"ميت سلسيل","city"=>"Meet Salsil"],
            // ["id"=>"153","city_id"=>"4","region"=>"جمصة","city"=>"Gamasa"],
            // ["id"=>"154","city_id"=>"4","region"=>"محلة دمنة","city"=>"Mahalat Damana"],
            // ["id"=>"155","city_id"=>"4","region"=>"نبروه","city"=>"Nabroh"],
            ["city_id"=>"5","region"=>"الغردقة"],
            ["city_id"=>"5","region"=>"رأس غارب"],
            ["city_id"=>"5","region"=>"سفاجا"],
            // ["id"=>"159","city_id"=>"5","region"=>"القصير","city"=>"El Qusiar"],
            // ["id"=>"160","city_id"=>"5","region"=>"مرسى علم","city"=>"Marsa Alam"],
            // ["id"=>"161","city_id"=>"5","region"=>"الشلاتين","city"=>"Shalatin"],
            // ["id"=>"162","city_id"=>"5","region"=>"حلايب","city"=>"Halaib"],
            // ["id"=>"163","city_id"=>"5","region"=>"الدهار","city"=>"Aldahar"],
            // ["id"=>"164","city_id"=>"6","region"=>"دمنهور","city"=>"Damanhour"],
            // ["id"=>"165","city_id"=>"6","region"=>"كفر الدوار","city"=>"Kafr El Dawar"],
            // ["id"=>"166","city_id"=>"6","region"=>"رشيد","city"=>"Rashid"],
            // ["id"=>"167","city_id"=>"6","region"=>"إدكو","city"=>"Edco"],
            // ["id"=>"168","city_id"=>"6","region"=>"أبو المطامير","city"=>"Abu al-Matamir"],
            // ["id"=>"169","city_id"=>"6","region"=>"أبو حمص","city"=>"Abu Homs"],
            // ["id"=>"170","city_id"=>"6","region"=>"الدلنجات","city"=>"Delengat"],
            // ["id"=>"171","city_id"=>"6","region"=>"المحمودية","city"=>"Mahmoudiyah"],
            // ["id"=>"172","city_id"=>"6","region"=>"الرحمانية","city"=>"Rahmaniyah"],
            // ["id"=>"173","city_id"=>"6","region"=>"إيتاي البارود","city"=>"Itai Baroud"],
            // ["id"=>"174","city_id"=>"6","region"=>"حوش عيسى","city"=>"Housh Eissa"],
            // ["id"=>"175","city_id"=>"6","region"=>"شبراخيت","city"=>"Shubrakhit"],
            // ["id"=>"176","city_id"=>"6","region"=>"كوم حمادة","city"=>"Kom Hamada"],
            ["city_id"=>"6","region"=>"بدر"],
            // ["id"=>"178","city_id"=>"6","region"=>"وادي النطرون","city"=>"Wadi Natrun"],
             ["city_id"=>"6","region"=>"النوبارية الجديدة"],
            //["id"=>"180","city_id"=>"6","region"=>"النوبارية","city"=>"Alnoubareya"],
             ["city_id"=>"7","region"=>"الفيوم"],
            // ["id"=>"182","city_id"=>"7","region"=>"الفيوم الجديدة","city"=>"Fayoum El Gedida"],
            // ["id"=>"183","city_id"=>"7","region"=>"طامية","city"=>"Tamiya"],
            // ["id"=>"184","city_id"=>"7","region"=>"سنورس","city"=>"Snores"],
            // ["id"=>"185","city_id"=>"7","region"=>"إطسا","city"=>"Etsa"],
            // ["id"=>"186","city_id"=>"7","region"=>"إبشواي","city"=>"Epschway"],
             ["city_id"=>"7","region"=>"يوسف الصديق"],
            // ["id"=>"188","city_id"=>"7","region"=>"الحادقة","city"=>"Hadqa"],
            // ["id"=>"189","city_id"=>"7","region"=>"اطسا","city"=>"Atsa"],
            // ["id"=>"190","city_id"=>"7","region"=>"الجامعة","city"=>"Algamaa"],
            // ["id"=>"191","city_id"=>"7","region"=>"السيالة","city"=>"Sayala"],
            ["city_id"=>"8","region"=>"طنطا"],
            ["city_id"=>"8","region"=>"المحلة الكبرى"],
            // ["id"=>"194","city_id"=>"8","region"=>"كفر الزيات","city"=>"Kafr El Zayat"],
            // ["id"=>"195","city_id"=>"8","region"=>"زفتى","city"=>"Zefta"],
            // ["id"=>"196","city_id"=>"8","region"=>"السنطة","city"=>"El Santa"],
            // ["id"=>"197","city_id"=>"8","region"=>"قطور","city"=>"Qutour"],
            // ["id"=>"198","city_id"=>"8","region"=>"بسيون","city"=>"Basion"],
            // ["id"=>"199","city_id"=>"8","region"=>"سمنود","city"=>"Samannoud"],
            ["city_id"=>"9","region"=>"الإسماعيلية"],
            ["city_id"=>"9","region"=>"فايد"],
            ["city_id"=>"9","region"=>"القنطرة شرق"],
            // ["id"=>"203","city_id"=>"9","region"=>"القنطرة غرب","city"=>"Qantara Gharb"],
            // ["id"=>"204","city_id"=>"9","region"=>"التل الكبير","city"=>"El Tal El Kabier"],
            // ["id"=>"205","city_id"=>"9","region"=>"أبو صوير","city"=>"Abu Sawir"],
            // ["id"=>"206","city_id"=>"9","region"=>"القصاصين الجديدة","city"=>"Kasasien El Gedida"],
            // ["id"=>"207","city_id"=>"9","region"=>"نفيشة","city"=>"Nefesha"],
            // ["id"=>"208","city_id"=>"9","region"=>"الشيخ زايد","city"=>"Sheikh Zayed"],
            // ["id"=>"209","city_id"=>"10","region"=>"شبين الكوم","city"=>"Shbeen El Koom"],
            ["city_id"=>"10","region"=>"مدينة السادات"],
            // ["id"=>"211","city_id"=>"10","region"=>"منوف","city"=>"Menouf"],
            // ["id"=>"212","city_id"=>"10","region"=>"سرس الليان","city"=>"Sars El-Layan"],
            // ["id"=>"213","city_id"=>"10","region"=>"أشمون","city"=>"Ashmon"],
            // ["id"=>"214","city_id"=>"10","region"=>"الباجور","city"=>"Al Bagor"],
            // ["id"=>"215","city_id"=>"10","region"=>"قويسنا","city"=>"Quesna"],
            // ["id"=>"216","city_id"=>"10","region"=>"بركة السبع","city"=>"Berkat El Saba"],
            ["city_id"=>"10","region"=>"تلا"],
            // ["id"=>"218","city_id"=>"10","region"=>"الشهداء","city"=>"Al Shohada"],
            ["city_id"=>"11","region"=>"المنيا"],
            // ["id"=>"220","city_id"=>"11","region"=>"المنيا الجديدة","city"=>"Minya El Gedida"],
            // ["id"=>"221","city_id"=>"11","region"=>"العدوة","city"=>"El Adwa"],
            // ["id"=>"222","city_id"=>"11","region"=>"مغاغة","city"=>"Magagha"],
            // ["id"=>"223","city_id"=>"11","region"=>"بني مزار","city"=>"Bani Mazar"],
            // ["id"=>"224","city_id"=>"11","region"=>"مطاي","city"=>"Mattay"],
            // ["id"=>"225","city_id"=>"11","region"=>"سمالوط","city"=>"Samalut"],
            // ["id"=>"226","city_id"=>"11","region"=>"المدينة الفكرية","city"=>"Madinat El Fekria"],
            // ["id"=>"227","city_id"=>"11","region"=>"ملوي","city"=>"Meloy"],
            // ["id"=>"228","city_id"=>"11","region"=>"دير مواس","city"=>"Deir Mawas"],
            ["city_id"=>"11","region"=>"ابو قرقاص"],
            // ["id"=>"230","city_id"=>"11","region"=>"ارض سلطان","city"=>"Ard Sultan"],
            // ["id"=>"231","city_id"=>"12","region"=>"بنها","city"=>"Banha"],
            // ["id"=>"232","city_id"=>"12","region"=>"قليوب","city"=>"Qalyub"],
            // ["id"=>"233","city_id"=>"12","region"=>"شبرا الخيمة","city"=>"Shubra Al Khaimah"],
            ["city_id"=>"12","region"=>"القناطر الخيرية"],
            // ["id"=>"235","city_id"=>"12","region"=>"الخانكة","city"=>"Khanka"],
            // ["id"=>"236","city_id"=>"12","region"=>"كفر شكر","city"=>"Kafr Shukr"],
            // ["id"=>"237","city_id"=>"12","region"=>"طوخ","city"=>"Tukh"],
            // ["id"=>"238","city_id"=>"12","region"=>"قها","city"=>"Qaha"],
            ["city_id"=>"12","region"=>"العبور"],
            // ["id"=>"240","city_id"=>"12","region"=>"الخصوص","city"=>"Khosous"],
            // ["id"=>"241","city_id"=>"12","region"=>"شبين القناطر","city"=>"Shibin Al Qanater"],
            // ["id"=>"242","city_id"=>"12","region"=>"مسطرد","city"=>"Mostorod"],
            // ["id"=>"243","city_id"=>"13","region"=>"الخارجة","city"=>"El Kharga"],
            // ["id"=>"244","city_id"=>"13","region"=>"باريس","city"=>"Paris"],
            // ["id"=>"245","city_id"=>"13","region"=>"موط","city"=>"Mout"],
            ["city_id"=>"13","region"=>"لفرافرة"],
            // ["city_id"=>"13","city"=>"Balat"],
            // ["city_id"=>"13","city"=>"Dakhla"],
            // ["city_id"=>"14","city"=>"Suez"],
            // ["id"=>"250","city_id"=>"14","region"=>"الجناين","city"=>"Alganayen"],
            // ["id"=>"251","city_id"=>"14","region"=>"عتاقة","city"=>"Ataqah"],
            // ["id"=>"252","city_id"=>"14","region"=>"العين السخنة","city"=>"Ain Sokhna"],
            // ["id"=>"253","city_id"=>"14","region"=>"فيصل","city"=>"Faysal"],
            // ["id"=>"254","city_id"=>"15","region"=>"أسوان","city"=>"Aswan"],
            // ["id"=>"255","city_id"=>"15","region"=>"أسوان الجديدة","city"=>"Aswan El Gedida"],
            // ["id"=>"256","city_id"=>"15","region"=>"دراو","city"=>"Drau"],
            // ["id"=>"257","city_id"=>"15","region"=>"كوم أمبو","city"=>"Kom Ombo"],
            // ["id"=>"258","city_id"=>"15","region"=>"نصر النوبة","city"=>"Nasr Al Nuba"],
            // ["id"=>"259","city_id"=>"15","region"=>"كلابشة","city"=>"Kalabsha"],
            // ["id"=>"260","city_id"=>"15","region"=>"إدفو","city"=>"Edfu"],
            // ["id"=>"261","city_id"=>"15","region"=>"الرديسية","city"=>"Al-Radisiyah"],
            // ["city_id"=>"15","city"=>"Al Basilia"],
            // ["city_id"=>"15","city"=>"Al Sibaeia"],
            ["city_id"=>"15","region"=>"إبوسمبل السياحية"],
            // ["id"=>"265","city_id"=>"15","region"=>"مرسى علم","city"=>"Marsa Alam"],
            ["city_id"=>"16","region"=>"أسيوط"],
            // ["id"=>"267","city_id"=>"16","region"=>"أسيوط الجديدة","city"=>"Assiut El Gedida"],
            // ["id"=>"268","city_id"=>"16","region"=>"ديروط","city"=>"Dayrout"],
            // ["id"=>"269","city_id"=>"16","region"=>"منفلوط","city"=>"Manfalut"],
            // ["id"=>"270","city_id"=>"16","region"=>"القوصية","city"=>"Qusiya"],
            // ["id"=>"271","city_id"=>"16","region"=>"أبنوب","city"=>"Abnoub"],
            // ["id"=>"272","city_id"=>"16","region"=>"أبو تيج","city"=>"Abu Tig"],
            // ["id"=>"273","city_id"=>"16","region"=>"الغنايم","city"=>"El Ghanaim"],
            // ["id"=>"274","city_id"=>"16","region"=>"ساحل سليم","city"=>"Sahel Selim"],
            // ["id"=>"275","city_id"=>"16","region"=>"البداري","city"=>"El Badari"],
            // ["id"=>"276","city_id"=>"16","region"=>"صدفا","city"=>"Sidfa"],
            // ["id"=>"277","city_id"=>"17","region"=>"بني سويف","city"=>"Bani Sweif"],
            ["city_id"=>"17","region"=>"بني سويف الجديدة"],
            // ["city_id"=>"17","city"=>"Al Wasta"],
            // ["city_id"=>"17","city"=>"Naser"],
            // ["city_id"=>"17","city"=>"Ehnasia"],
            // ["city_id"=>"17","city"=>"beba"],
            // ["city_id"=>"17","city"=>"Fashn"],
            // ["city_id"=>"17","city"=>"Somasta"],
            // ["city_id"=>"17","city"=>"Alabbaseri"],
            // ["id"=>"286","city_id"=>"17","region"=>"مقبل","city"=>"Mokbel"],
            // ["id"=>"287","city_id"=>"18","region"=>"بورسعيد","city"=>"PorSaid"],
            // ["id"=>"288","city_id"=>"18","region"=>"بورفؤاد","city"=>"Port Fouad"],
            // ["id"=>"289","city_id"=>"18","region"=>"العرب","city"=>"Alarab"],
            ["city_id"=>"18","region"=>"حى الزهور"],
            ["city_id"=>"18","region"=>"حى الشرق"],
            // ["id"=>"292","city_id"=>"18","region"=>"حى الضواحى","city"=>"Aldawahi"],
            // ["id"=>"293","city_id"=>"18","region"=>"حى المناخ","city"=>"Almanakh"],
            // ["id"=>"294","city_id"=>"18","region"=>"حى مبارك","city"=>"Mubarak"],
            // ["id"=>"295","city_id"=>"19","region"=>"دمياط","city"=>"Damietta"],
            // ["id"=>"296","city_id"=>"19","region"=>"دمياط الجديدة","city"=>"New Damietta"],
            ["city_id"=>"19","region"=>"رأس البر"],
            ["city_id"=>"19","region"=>"فارسكور"],
            // ["id"=>"299","city_id"=>"19","region"=>"الزرقا","city"=>"Zarqa"],
            // ["id"=>"300","city_id"=>"19","region"=>"السرو","city"=>"alsaru"],
            // ["id"=>"301","city_id"=>"19","region"=>"الروضة","city"=>"alruwda"],
            // ["id"=>"302","city_id"=>"19","region"=>"كفر البطيخ","city"=>"Kafr El-Batikh"],
            // ["id"=>"303","city_id"=>"19","region"=>"عزبة البرج","city"=>"Azbet Al Burg"],
            // ["id"=>"304","city_id"=>"19","region"=>"ميت أبو غالب","city"=>"Meet Abou Ghalib"],
            // ["id"=>"305","city_id"=>"19","region"=>"كفر سعد","city"=>"Kafr Saad"],
            ["city_id"=>"20","region"=>"الزقازيق"],
            ["city_id"=>"20","region"=>"العاشر من رمضان"],
            // ["id"=>"308","city_id"=>"20","region"=>"منيا القمح","city"=>"Minya Al Qamh"],
            // ["id"=>"309","city_id"=>"20","region"=>"بلبيس","city"=>"Belbeis"],
            // ["id"=>"310","city_id"=>"20","region"=>"مشتول السوق","city"=>"Mashtoul El Souq"],
            // ["id"=>"311","city_id"=>"20","region"=>"القنايات","city"=>"Qenaiat"],
            // ["id"=>"312","city_id"=>"20","region"=>"أبو حماد","city"=>"Abu Hammad"],
            // ["id"=>"313","city_id"=>"20","region"=>"القرين","city"=>"El Qurain"],
            // ["id"=>"314","city_id"=>"20","region"=>"ههيا","city"=>"Hehia"],
            // ["id"=>"315","city_id"=>"20","region"=>"أبو كبير","city"=>"Abu Kabir"],
            // ["id"=>"316","city_id"=>"20","region"=>"فاقوس","city"=>"Faccus"],
            // ["id"=>"317","city_id"=>"20","region"=>"الصالحية الجديدة","city"=>"El Salihia El Gedida"],
            // ["id"=>"318","city_id"=>"20","region"=>"الإبراهيمية","city"=>"Al Ibrahimiyah"],
            // ["id"=>"319","city_id"=>"20","region"=>"ديرب نجم","city"=>"Deirb Negm"],
            // ["id"=>"320","city_id"=>"20","region"=>"كفر صقر","city"=>"Kafr Saqr"],
            // ["id"=>"321","city_id"=>"20","region"=>"أولاد صقر","city"=>"Awlad Saqr"],
            // ["id"=>"322","city_id"=>"20","region"=>"الحسينية","city"=>"Husseiniya"],
            // ["id"=>"323","city_id"=>"20","region"=>"صان الحجر القبلية","city"=>"san alhajar alqablia"],
            // ["id"=>"324","city_id"=>"20","region"=>"منشأة أبو عمر","city"=>"Manshayat Abu Omar"],
            // ["id"=>"325","city_id"=>"21","region"=>"الطور","city"=>"Al Toor"],
            ["city_id"=>"21","region"=>"شرم الشيخ"],
            ["city_id"=>"21","region"=>"دهب"],
            ["city_id"=>"21","region"=>"نويبع"],
            ["city_id"=>"21","region"=>"طابا"],
            ["city_id"=>"21","region"=>"سانت كاترين",],
            // ["id"=>"331","city_id"=>"21","region"=>"أبو رديس","city"=>"Abu Redis"],
            // ["id"=>"332","city_id"=>"21","region"=>"أبو زنيمة","city"=>"Abu Zenaima"],
            // ["id"=>"333","city_id"=>"21","region"=>"رأس سدر","city"=>"Ras Sidr"],
            ["city_id"=>"22","region"=>"كفر الشيخ"],
            // ["id"=>"335","city_id"=>"22","region"=>"وسط البلد كفر الشيخ","city"=>"Kafr El Sheikh Downtown"],
            ["city_id"=>"22","region"=>"دسوق"],
            // ["id"=>"337","city_id"=>"22","region"=>"فوه","city"=>"Fooh"],
            // ["id"=>"338","city_id"=>"22","region"=>"مطوبس","city"=>"Metobas"],
            // ["id"=>"339","city_id"=>"22","region"=>"برج البرلس","city"=>"Burg Al Burullus"],
            // ["id"=>"340","city_id"=>"22","region"=>"بلطيم","city"=>"Baltim"],
            // ["id"=>"341","city_id"=>"22","region"=>"مصيف بلطيم","city"=>"Masief Baltim"],
            // ["id"=>"342","city_id"=>"22","region"=>"الحامول","city"=>"Hamol"],
            // ["id"=>"343","city_id"=>"22","region"=>"بيلا","city"=>"Bella"],
            // ["id"=>"344","city_id"=>"22","region"=>"الرياض","city"=>"Riyadh"],
            // ["id"=>"345","city_id"=>"22","region"=>"سيدي سالم","city"=>"Sidi Salm"],
            // ["id"=>"346","city_id"=>"22","region"=>"قلين","city"=>"Qellen"],
            // ["id"=>"347","city_id"=>"22","region"=>"سيدي غازي","city"=>"Sidi Ghazi"],
            ["city_id"=>"23","region"=>"مرسى مطروح"],
            // ["id"=>"349","city_id"=>"23","region"=>"الحمام","city"=>"El Hamam"],
            ["city_id"=>"23","region"=>"العلمين"],
            // ["id"=>"351","city_id"=>"23","region"=>"الضبعة","city"=>"Dabaa"],
            // ["id"=>"352","city_id"=>"23","region"=>"النجيلة","city"=>"Al-Nagila"],
            // ["id"=>"353","city_id"=>"23","region"=>"سيدي براني","city"=>"Sidi Brani"],
            // ["id"=>"354","city_id"=>"23","region"=>"السلوم","city"=>"Salloum"],
            // ["id"=>"355","city_id"=>"23","region"=>"سيوة","city"=>"Siwa"],
            // ["id"=>"356","city_id"=>"23","region"=>"مارينا","city"=>"Marina"],
            // ["id"=>"357","city_id"=>"23","region"=>"الساحل الشمالى","city"=>"North Coast"],
             ["city_id"=>"24","region"=>"الأقصر"],
            // ["id"=>"359","city_id"=>"24","region"=>"الأقصر الجديدة","city"=>"New Luxor"],
             ["city_id"=>"24","region"=>"إسنا"],
            // ["id"=>"361","city_id"=>"24","region"=>"طيبة الجديدة","city"=>"New Tiba"],
            // ["id"=>"362","city_id"=>"24","region"=>"الزينية","city"=>"Al ziynia"],
            // ["id"=>"363","city_id"=>"24","region"=>"البياضية","city"=>"Al Bayadieh"],
            // ["id"=>"364","city_id"=>"24","region"=>"القرنة","city"=>"Al Qarna"],
            // ["id"=>"365","city_id"=>"24","region"=>"أرمنت","city"=>"Armant"],
            // ["id"=>"366","city_id"=>"24","region"=>"الطود","city"=>"Al Tud"],
            ["city_id"=>"25","region"=>"قنا"],
            // ["id"=>"368","city_id"=>"25","region"=>"قنا الجديدة","city"=>"New Qena"],
            // ["id"=>"369","city_id"=>"25","region"=>"ابو طشت","city"=>"Abu Tesht"],
            // ["id"=>"370","city_id"=>"25","region"=>"نجع حمادي","city"=>"Nag Hammadi"],
            // ["id"=>"371","city_id"=>"25","region"=>"دشنا","city"=>"Deshna"],
            // ["id"=>"372","city_id"=>"25","region"=>"الوقف","city"=>"Alwaqf"],
            // ["id"=>"373","city_id"=>"25","region"=>"قفط","city"=>"Qaft"],
            // ["id"=>"374","city_id"=>"25","region"=>"نقادة","city"=>"Naqada"],
            // ["id"=>"375","city_id"=>"25","region"=>"فرشوط","city"=>"Farshout"],
            // ["id"=>"376","city_id"=>"25","region"=>"قوص","city"=>"Quos"],
            ["city_id"=>"26","region"=>"العريش"],
            // ["id"=>"378","city_id"=>"26","region"=>"الشيخ زويد","city"=>"Sheikh Zowaid"],
            // ["id"=>"379","city_id"=>"26","region"=>"نخل","city"=>"Nakhl"],
            // ["id"=>"380","city_id"=>"26","region"=>"رفح","city"=>"Rafah"],
            // ["id"=>"381","city_id"=>"26","region"=>"بئر العبد","city"=>"Bir al-Abed"],
            // ["id"=>"382","city_id"=>"26","region"=>"الحسنة","city"=>"Al Hasana"],
            ["city_id"=>"27","region"=>"سوهاج"],
            // ["id"=>"384","city_id"=>"27","region"=>"سوهاج الجديدة","city"=>"Sohag El Gedida"],
            // ["id"=>"385","city_id"=>"27","region"=>"أخميم","city"=>"Akhmeem"],
            // ["id"=>"386","city_id"=>"27","region"=>"أخميم الجديدة","city"=>"Akhmim El Gedida"],
            // ["id"=>"387","city_id"=>"27","region"=>"البلينا","city"=>"Albalina"],
            // ["id"=>"388","city_id"=>"27","region"=>"المراغة","city"=>"El Maragha"],
            // ["id"=>"389","city_id"=>"27","region"=>"المنشأة","city"=>"almunsha'a"],
            // ["id"=>"390","city_id"=>"27","region"=>"دار السلام","city"=>"Dar AISalaam"],
            // ["id"=>"391","city_id"=>"27","region"=>"جرجا","city"=>"Gerga"],
            // ["id"=>"392","city_id"=>"27","region"=>"جهينة الغربية","city"=>"Jahina Al Gharbia"],
            // ["id"=>"393","city_id"=>"27","region"=>"ساقلته","city"=>"Saqilatuh"],
            // ["id"=>"394","city_id"=>"27","region"=>"طما","city"=>"Tama"],
            // ["id"=>"395","city_id"=>"27","region"=>"طهطا","city"=>"Tahta"],
            // ["id"=>"396","city_id"=>"27","region"=>"الكوثر","city"=>"Alkawthar"]
        ];

        foreach ($regions as $reg) {
            Region::create(
                [
                    'city_id' => $reg['city_id'],
                    'name' => $reg['region'],
                ],
            );
        }
    }
}
